services:
  webshop.website:
    image: webapp
    container_name: webshop.website
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AppConnection=Host=webshop.database;Port=5331;Database=webshop;Username=postgres;Password=postgres
    networks:
      - webshop-network
    ports:
      - "8077:8080"
    depends_on:
      webshop.database:
        condition: service_healthy
  
  webshop.database:
    image: postgres:18
    container_name: webshop.database
    environment:
      - POSTGRES_DB=webshop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - webshop-network
    volumes:
      - "webshop-db:/var/lib/postgresql"
    ports:
      - "5331:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  webshop-db:
networks:
  webshop-network: