services:
  webshop.website:
    image: docker.io/darklord200/webapp:latest
    container_name: webshop.website
    build:
      context: .
      dockerfile: webapp.Dockerfile
    env_file:
      - .env.docker
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AppConnection=Host=webshop.database;Port=5432;Database=webshop;Username=postgres;Password=postgres
    networks:
      - webshop-network
    ports:
      - "8077:8080"
    depends_on:
      webshop.database:
        condition: service_healthy
      webshop.webapi:
        condition: service_started
      webshop.duende:
        condition: service_started
  
  webshop.database:
    image: postgres:18
    container_name: webshop.database
    environment:
      - POSTGRES_DB=webshop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - webshop-network
    volumes:
      - "webshop-db:/var/lib/postgresql"
    ports:
      - "5331:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  webshop.webapi:
    image: docker.io/darklord200/webapi:latest
    container_name: webshop.webapi
    build:
      context: .
      dockerfile: webapi.Dockerfile
    env_file:
      - .env.docker
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__StockWebApiConnection=Host=webapi.database;Port=5432;Database=webapi;Username=postgres;Password=postgres
    networks:
      - webshop-network
    ports:
      - "8078:8080"
    depends_on:
      webapi.database:
        condition: service_healthy
  
  webapi.database:
    image: postgres:18
    container_name: webapi.database
    environment:
      - POSTGRES_DB=webapi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - webshop-network
    volumes:
      - "webapi-db:/var/lib/postgresql"
    ports:
      - "5931:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  webshop.duende:
    image: docker.io/darklord200/duende:latest
    container_name: webshop.duende
    build:
      context: .
      dockerfile: ./DuendeIdentityServer/Duende.Dockerfile
    env_file:
      - .env.docker
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AppConnection=Host=webshop.database;Port=5432;Database=webshop;Username=postgres;Password=postgres
    networks:
      - webshop-network
    ports:
      - "8080:8080"
    depends_on:
      webshop.database:
        condition: service_healthy

volumes:
  webshop-db:
  webapi-db:
networks:
  webshop-network:
